name: Build All Presets

on:
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build-matrix:
    name: ${{ matrix.preset }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        preset:
          - FTS
          - TOOL_CONTROL
          - J3_4_CONTROL
          - J2_CONTROL
          - J1_CONTROL
          - LED
          - DECK_SLOT
          - INTERMODULARITY
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install ARM toolchain and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi ninja-build

      - name: Debug Build - ${{ matrix.preset }}
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build build/${{ matrix.preset }}

      - name: Release Build - ${{ matrix.preset }}
        run: |
          cmake --preset ${{ matrix.preset }}-Release
          cmake --build build/${{ matrix.preset }}-Release
