[package]
name = "cansender"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
dialoguer = "0.12.0"
embedded-can = "0.4.1"
futures-timer = "3.0.4"
indicatif = "0.18.4"
socketcan = { version = "3.5.0", features = ["tokio"] }
strum = "0.28.0"
strum_macros = "0.28.0"
tokio = { version = "1.52.3", features = ["full"] }
